---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: ':pipeline: Validate catalogs'
    command: 'npm ci --ignore-scripts && npm run check'
    timeout_in_minutes: 15
    agents:
      image: 'docker.elastic.co/ci-agent-images/kibana/chainguard-nodejs-20'
