# =============================================================================
# Workflow: createCaseTool
# Category: security/response
#
# Creates a new case using the Kibana Cases API. Supports configurable
# severity and creates cases under the Security Solution owner so they
# appear in Security > Cases rather than Observability.
#
# Author: Elastic
# Created: 2025-11-19
# Tags: Security, AgentTool
# =============================================================================
name: createCaseTool
description: A tool that lets an Agent create a Security case
enabled: true

# ---------------------------------------------------------------------------
# TRIGGERS
# ---------------------------------------------------------------------------
triggers:
  - type: manual

# ---------------------------------------------------------------------------
# TAGS
# ---------------------------------------------------------------------------
tags: ["Security", "AgentTool"]

# ---------------------------------------------------------------------------
# INPUTS
# ---------------------------------------------------------------------------
inputs:
  - name: caseDescription
    required: true
    type: string
    description: "Detailed description of the incident or investigation"
  - name: caseTitle
    required: true
    type: string
    description: "Title for the case"
  - name: severity
    type: string
    description: "Case severity: low, medium, high, critical"
    default: "medium"

# ---------------------------------------------------------------------------
# STEPS
# ---------------------------------------------------------------------------
steps:

  # -------------------------------------------------------------------------
  # STEP 1: kibana_createCaseDefaultSpace_step
  # -------------------------------------------------------------------------
  # Creates a new case using the Kibana Cases API (POST /api/cases).
  # Owner is set to "securitySolution" so cases appear under
  # Security > Cases in Kibana, not the Observability cases view.
  # Severity is configurable via the severity input (defaults to medium).
  # Output: {{ steps.kibana_createCaseDefaultSpace_step.output.id }}
  # -------------------------------------------------------------------------
  - name: kibana_createCaseDefaultSpace_step
    type: kibana.createCaseDefaultSpace
    with:
      connector:
        fields: null
        id: none
        name: none
        type: .none
      description: |
        {{ inputs.caseDescription }}
      owner: securitySolution
      settings:
        syncAlerts: true
      severity: "{{ inputs.severity }}"
      tags:
        - Automatic
      title: "{{ inputs.caseTitle }}"
