name: Reusable workflow example

on:
  workflow_call:
    inputs:
      prebuild: 
        type: string
        required: true
      project-name: 
        type: string
        required: true
      repo: 
        type: string
        required: true
    secrets:
      VERCEL_GITHUB_TOKEN:
        description: 'A GitHub PAT with repo scope'
        required: true
      VERCEL_TOKEN:
        description: 'Vercel API token, account level'
        required: true
      VERCEL_ORG_ID:
        description: 'Vercel ORG token, org level'
        required: true
      VERCEL_PROJECT_ID_DOCS_CO:
        description: 'Vercel PROJECT token, project level'
        required: true

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:

      - name: Setup workspace
        uses: actions/checkout@v3.0.1

      - name: Checkout current branch into temp
        if: github.event.pull_request.merged == false
        uses: actions/checkout@v3.0.1
        with:
          path: 'tmp'
          fetch-depth: 2
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Checkout essential repos
        uses: actions/checkout@v3.0.1
        with:
          repository: elastic/${{ inputs.repo }}
          token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          path: ${{ github.workspace }}/${{ inputs.repo }}

      - name: Checkout Wordlake
        uses: actions/checkout@v3.0.1
        with:
          repository: elastic/${{ inputs.prebuild }}
          token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          path: ${{ github.workspace }}/${{ inputs.prebuild }}

      - name: Show current workspace
        shell: bash
        run: ls -lat 

      - name: Show child workspace
        shell: bash
        run: ls -lat ${{ github.workspace }}

      - name: Show parent workspace
        shell: bash
        run: ls -lat ..

      - name: Portal
        shell: bash
        run: |
          mkdir -p ${{ github.workspace }}/${{ inputs.prebuild }}/${{ github.event.repository.name }}
          rm -rf ${{ github.workspace }}/${{ inputs.prebuild }}/${{ github.event.repository.name }}/*
          rsync --ignore-missing-args -zavpm \
          --exclude='cats.mdx' \
          --include='*.docnav.json' \
          --include='*.apidocs.json' \
          --include='*.mdx' \
          --include='*.png' \
          --include='*.gif' \
          --include='*.jpg' \
          --include='*.jpeg' \
          --include='*.devdocs.json' \
          --include='*/' \
          --exclude='*' \
          ${{ github.workspace }}/tmp/ \
          ${{ github.workspace }}/${{ inputs.prebuild }}/${{ github.event.repository.name }}/

      - name: Generate preview
        if: github.event.pull_request.merged == false
        uses: elastic/builder@v21.3.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_DOCS_CO }} #Required
          vercel-project-name: ${{ inputs.project-name }}
          working-directory: ./
          github-comment: false # Otherwise need github-token (VERCEL_GITHUB_TOKEN)