name: Portal

on:
  workflow_call:
    inputs:
      prebuild: 
        type: string
        required: true
    secrets:
      token:
        required: true

jobs:
  deploy:
    name: Portal
    runs-on: ubuntu-latest
    steps:

      - name: Cache job
        uses: actions/cache@v3
        with:
          path: *
          key: ${{ github.event.pull_request.number }}-docs

      - name: Show workspace
        shell: bash
        run: ls -lat ${{ github.workspace }}

      - name: Portal
        shell: bash
        run: |
          mkdir -p ${{ github.workspace }}/${{ inputs.prebuild }}/${{ github.event.repository.name }}
          rm -rf ${{ github.workspace }}/${{ inputs.prebuild }}/${{ github.event.repository.name }}/*
          rsync --ignore-missing-args -zavpm \
          --exclude='cats.mdx' \
          --include='*.docnav.json' \
          --include='*.apidocs.json' \
          --include='*.mdx' \
          --include='*.png' \
          --include='*.gif' \
          --include='*.jpg' \
          --include='*.jpeg' \
          --include='*.devdocs.json' \
          --include='*/' \
          --exclude='*' \
          ${{ github.workspace }}/tmp/ \
          ${{ github.workspace }}/${{ inputs.prebuild }}/${{ github.event.repository.name }}/