name: Deploy

on:
  workflow_call:
    inputs:
      prebuild:
        required: true
        type: string
    secrets:
      VERCEL_GITHUB_TOKEN:
        description: 'A GitHub PAT with repo scope'
        required: true

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Wordlake for commit
        uses: actions/checkout@v3.0.1
        with:
          repository: elastic/${{ inputs.prebuild }}
          token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          path: ${{ github.workspace }}/${{ inputs.prebuild }}
      
      - name: Portal for deploy
        if: github.event.pull_request.merged == true
        shell: bash
        run: |
          cd ${{ github.workspace }}/${{ inputs.prebuild }}
          git config user.name count-docula
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "New content from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
          git push