name: Prepare

on:
  workflow_call:
    secrets:
      VERCEL_GITHUB_TOKEN:
        description: 'A GitHub PAT with repo scope'
        required: true
    inputs:
      prebuild: 
        type: string
        require: true
      repo: 
        type: string
        require: true
  pull_request_target:
    paths:
    # Change docs dir to your repos docs dir
      - 'docs/**.mdx'
      - 'docs/**.docnav.json'
      - 'docs/**.docapi.json'
      - 'docs/**.devdocs.json'
      - 'docs/**.jpg'
      - 'docs/**.jpeg'
      - 'docs/**.png'
      - 'docs/**.gif'
    types: [closed, opened, synchronize, reopened]

jobs:
 prepare:
    name: Prepare build
    runs-on: ubuntu-latest
    steps:

      - name: Setup workspace
        uses: actions/checkout@v3.0.1

      - name: Checkout current branch into temp
        if: github.event.pull_request.merged == false
        uses: actions/checkout@v3.0.1
        with:
          path: 'temp'
          fetch-depth: 2
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Checkout current branch into temp
        if: github.event.pull_request.merged == true
        uses: actions/checkout@v3.0.1
        with:
          path: 'tmp'

      - name: Checkout essential repos
        uses: actions/checkout@v3.0.1
        with:
          repository: elastic/${{ inputs.repo }}
          token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          path: ${{ github.workspace }}/${{ inputs.repo }}

      - name: Checkout Wordlake
        uses: actions/checkout@v3.0.1
        with:
          repository: elastic/${{ inputs.prebuild }}
          token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          path: ${{ github.workspace }}/${{ inputs.prebuild }}

      - name: Cache job
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: ${{ github.event.pull_request.number }}-docs-${GITHUB_SHA}