name: Prepare

on:
  workflow_call:
    secrets:
      VERCEL_GITHUB_TOKEN:
        description: 'A GitHub PAT with repo scope'
        required: true
    inputs:
      prebuild: 
        type: string
        required: true
      repo: 
        type: string
        required: true

jobs:
 prepare:
    name: Prepare build
    runs-on: ubuntu-latest
    steps:
      - name: Setup workspace
        uses: actions/checkout@v3.0.1

      - name: Checkout current branch into temp
        if: github.event.pull_request.merged == false
        uses: actions/checkout@v3.0.1
        with:
          path: 'tmp'
          fetch-depth: 2
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Checkout current branch into temp
        if: github.event.pull_request.merged == true
        uses: actions/checkout@v3.0.1
        with:
          path: 'tmp'

      - name: Checkout essential repos
        uses: actions/checkout@v3.0.1
        with:
          repository: elastic/${{ inputs.repo }}
          token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          path: ${{ github.workspace }}/${{ inputs.repo }}

      - name: Checkout Wordlake
        uses: actions/checkout@v3.0.1
        with:
          repository: elastic/${{ inputs.prebuild }}
          token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          path: ${{ github.workspace }}/${{ inputs.prebuild }}

      - name: Show current workspace
        shell: bash
        run: ls -lat 

      - name: Show child workspace
        shell: bash
        run: ls -lat ${{ github.workspace }}

      - name: Show parent workspace
        shell: bash
        run: ls -lat ..

      - uses: actions/upload-artifact@v2
        with:
          name: doc-bundle
          path: .
