name: builder

on:
  workflow_call:
    inputs:
      prebuild: 
        type: string
        required: true
      project-name: 
        type: string
        required: true
      repo: 
        type: string
        required: true
    secrets:
      VERCEL_GITHUB_TOKEN:
        description: 'A GitHub PAT with repo scope'
        required: true
      VERCEL_TOKEN:
        description: 'Vercel API token, account level'
        required: true
      VERCEL_ORG_ID:
        description: 'Vercel ORG token, org level'
        required: true
      VERCEL_PROJECT_ID_DOCS_CO:
        description: 'Vercel PROJECT token, project level'
        required: true

jobs:
  preview:
    name: doc builder
    runs-on: ubuntu-latest
    steps:

      - name: Setup workspace
        uses: actions/checkout@v3.0.1

      - name: Checkout current branch into temp
        if: github.event.pull_request.merged == false
        uses: actions/checkout@v3.0.1
        with:
          path: 'tmp'
          fetch-depth: 2
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
          
      - name: Checkout current branch into temp
        if: github.event.pull_request.merged == true
        uses: actions/checkout@v2
        with:
          path: 'tmp'

      - name: Checkout essential repos
        uses: actions/checkout@v3.0.1
        with:
          repository: elastic/${{ inputs.repo }}
          token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          path: ${{ github.workspace }}/${{ inputs.repo }}

      - name: Checkout Wordlake
        uses: actions/checkout@v3.0.1
        with:
          repository: elastic/${{ inputs.prebuild }}
          token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          path: ${{ github.workspace }}/${{ inputs.prebuild }}

      - name: Show current workspace
        shell: bash
        run: ls -lat 

      - name: Show child workspace
        shell: bash
        run: ls -lat ${{ github.workspace }}

      - name: Show parent workspace
        shell: bash
        run: ls -lat ..

      - name: Portal
        shell: bash
        run: |
          mkdir -p ${{ github.workspace }}/${{ inputs.prebuild }}/${{ github.event.repository.name }}
          rm -rf ${{ github.workspace }}/${{ inputs.prebuild }}/${{ github.event.repository.name }}/*
          rsync --ignore-missing-args -zavpm \
          --include='*.docnav.json' \
          --include='*.apidocs.json' \
          --include='*.mdx' \
          --include='*.png' \
          --include='*.gif' \
          --include='*.jpg' \
          --include='*.jpeg' \
          --include='*.devdocs.json' \
          --include='*/' \
          --exclude='*' \
          ${{ github.workspace }}/tmp/ \
          ${{ github.workspace }}/${{ inputs.prebuild }}/${{ github.event.repository.name }}/

      - name: Install Vercel CLI
        shell: bash
        run: | 
            npm install vercel@24.1.0

      - name: Generate preview
        if: github.event.pull_request.merged == false
        id: vercel-deploy
        uses: elastic/builder@v21.4.0
        continue-on-error: true
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_DOCS_CO }} #Required
          vercel-project-name: ${{ inputs.project-name }}
          working-directory: ./
          github-token: ${{ secrets.VERCEL_GITHUB_TOKEN }} #Optional 
          github-comment: true # Otherwise need github-token (VERCEL_GITHUB_TOKEN)

      - name: Declare Vercel failure
        if: steps.vercel-deploy.outcome != 'success'
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Deploy failed, see log in PR')

      - name: Get Vercel deploy URL
        if: always() && steps.vercel-deploy.outcome != 'success'
        shell: bash
        id: vercel-url
        run: | 
           echo "::set-output name=get-url::$(vercel list --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_ORG_ID }} | grep ERROR | sed -n 1p | sed -e 's/.*${{ inputs.project-name }}\(.*\)ERROR.*/\1/' | awk '{$1=$1};1')"

      - name: Process Vercel log
        if: always() && steps.vercel-deploy.outcome != 'success'
        id: vercel-log
        run: |
            VERCEL_LOG=$(vercel logs ${{ steps.vercel-url.outputs.get-url }} --output raw --token ${{ secrets.VERCEL_TOKEN }})
            VERCEL_LOG="${VERCEL_LOG//'%'/'%25'}"
            VERCEL_LOG="${VERCEL_LOG//$'\n'/'%0A'}"
            VERCEL_LOG="${VERCEL_LOG//$'\r'/'%0D'}"
            echo "::set-output name=get-log::$VERCEL_LOG"

      - name: Find existing bot comment
        if: always() && steps.vercel-deploy.outcome != 'success'
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Visit #next-docs in Slack'

      - name: Update existing bot comment
        if: always() && steps.fc.outputs.comment-id != '' && steps.vercel-deploy.outcome != 'success'
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            ---
              <details>
                <summary>Log for ${{ github.event.pull_request.head.sha }} </summary>

              ```bash

              ${{ steps.vercel-log.outputs.get-log }}
              
              ```
              
              </details>

      - name: Create new bot comment
        if: always() && steps.fc.outputs.comment-id == '' && steps.vercel-deploy.outcome != 'success'
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :exploding_head: _Error!_

            The docs build failed.

            Check below to see the log and troubleshoot.

            Stuck? Visit #next-docs in Slack.

            ---

              <details>
                <summary>Click to expand most recent error log >> </summary>

              ```bash

              ${{ steps.vercel-log.outputs.get-log }}
              
              ```
              
              </details>

      - name: Portal for deploy
        if: github.event.pull_request.merged == true
        shell: bash
        run: |
          cd ${{ github.workspace }}/${{ inputs.prebuild }}
          git config user.name count-docula
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "New content from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
          git push
